export const FETCH_USER = 'FETCH_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_USER = 'CREATE_USER';
export const STORE_USER_ERROR_MSG = 'USER_ERROR_MESSAGE';
export const STORE_SECRETS = 'STORE_SECRETS';
export const FETCH_USER_BALANCE = 'FETCH_USER_BALANCE';
export const GET_INTERNET_SERVICE_PROVIDER = 'GET_INTERNET_SERVICE_PROVIDER';
export const GET_AIRTIME_SERVICE_PROVIDER = 'GET_AIRTIME_SERVICE_PROVIDER';
export const GET_DISCOS = 'GET_DISCOS';
export const GET_INTERNET_PLANS = 'GET_INTERNET_PLANS';

